- README.md
- docker/.env
- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- helm/README.md
- helm/fiftyone-teams-app/.helmignore
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/templates/NOTES.txt
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/deployment.yaml
- helm/fiftyone-teams-app/templates/hpa.yaml
- helm/fiftyone-teams-app/templates/ingress.yaml
- helm/fiftyone-teams-app/templates/namespace.yaml
- helm/fiftyone-teams-app/templates/secrets.yaml
- helm/fiftyone-teams-app/templates/service.yaml
- helm/fiftyone-teams-app/templates/serviceaccount.yaml
- helm/fiftyone-teams-app/templates/tests/test-connection.yaml
- helm/gke-example/clusterissuer.yml
- helm/gke-example/values.yaml
- helm/values.yaml
This adds the current helm and docker deploy solutions and instructions
> adds helm and docker deploy options

- .github/workflows/release.yml
This should add a release workflow for helm charts.
> adds github workflow for chart releases

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- helm/fiftyone-teams-app/Chart.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
```
❯ ack '0.1.7'
❯ ack -i database_admin
docker/Dockerfile
112:    FIFTYONE_DATABASE_ADMIN=false \
docker/docker-compose.yml
19:      - FIFTYONE_DATABASE_ADMIN=false
helm/gke-example/values.yaml
29:    FIFTYONE_DATABASE_ADMIN: false
helm/values.yaml
29:    FIFTYONE_DATABASE_ADMIN: false
```
> Topher/fiftyone teams app v0.1.8

- terraform/README.md
- terraform/simple-two-node-deploy/google/appnode.tf
- terraform/simple-two-node-deploy/google/data.tf
- terraform/simple-two-node-deploy/google/dbnode.tf
- terraform/simple-two-node-deploy/google/output.tf
- terraform/simple-two-node-deploy/google/provider.tf
- terraform/simple-two-node-deploy/google/public-ssh-keys
- terraform/simple-two-node-deploy/google/terraform.tfvars
- terraform/simple-two-node-deploy/google/variables.tf
Adds a very simple terraform module for Google Cloud deployment.  This is probably primarily useful for small POC enviornments.
> adds simple terraform for app deploy options

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
Bump to v0.2.0
Update README to include upgrade/new-install procedures
Explicitly document that there is no default values.yml file
> bump to fiftyone-teams-app v0.2.0

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
releasing version 0.2.1 of `fiftyone-teams-app`
> bump to fiftyone-teams-app v0.2.1

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
> release `fiftyone-teams-app` v0.2.2

- docker/README.md
- docker/compose.yaml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
Adds Details regarding Text Similarity feature
Provides Upgrade Guidance for Early Adopters, versions less than v1.1, and version v1.1 or higher
adds the `FIFTYONE_INTERNAL_SERVICE` environment variable for `fiftyone-app` and `teams-api` services
> updates for Teams release v1.2.0

- docker/README.md
- helm/README.md
Update two 1.2.0 to 1.2.1 in the README.md for helm and docker
> Update version numbers in READMEs

- docker/README.md
- docker/compose.dedicated-plugins.yaml
- docker/compose.plugins.yaml
- docker/compose.yaml
- docker/docs/expose-teams-api.md
- helm/README.md
- helm/docs/expose-teams-api.md
- helm/docs/plugins-storage.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/values.yaml
- terraform/README.md
While reviewing the docs, I figured it would be good to leave them better than when I found them.
I changed the destination branch to the release branch so as to not trigger a release.  ~As I write this, I realized that I should have branched from this release branch, instead of main. Oops.~ I validated that the git branches `release/v1.4.0` and `main` have identical readme files:
```
$ git diff main remotes/origin/release/v1.4.0 --name-only
$
```
> docs review - edit and format exiting content.

- .github/CODEOWNERS
- .gitignore
- helm/README.md
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
After running through my first installation, I noticed a few enhancements to the repo and our documentation.
* Add .github/CODEOWNERS to assist in PR reviewer assignments
* Docs
* values.yaml
* #39 - This branch is based on the branch for that PR
> A few docs improvements after initial install

- helm/docs/expose-teams-api.md
Let's cherry-pick the changes from https://github.com/voxel51/fiftyone-teams-app-deploy/pull/55/files merged into the branch `release/v1.5.0` into the the branch `release/v1.4.3`.
> Cherry pick docs helm expose teams api

- docker/README.md
- docker/compose.dedicated-plugins.yaml
- docker/compose.plugins.yaml
- docker/compose.yaml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
> v1.4.5 release branch

- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
Bump compatibility version, release version, and sdk version in preparation for release
> bump version numbers for release

- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
Update documentation, helm charts, and docker-compose files for v1.5.3
> Merge release v1.5.3 into main

- .github/CODEOWNERS
- .github/pull_request_template.md
PR Templates help contributors to communicate a set of information when submitting a new pull request. We've used this template in a few other repos, so let's add this here.
* Add PR Template
PR template used in this PR description
> Add PR Template and codeowners File

- helm/fiftyone-teams-app/templates/_helpers.tpl
Add new and missing env vars for CAS
Added and removed some env vars for teams-api,app, cas, plugins, and teams-app  
Not yet tested
> add new cas env vars

- CONTRIBUTING.md
- helm/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/values.yaml
User reported broken docs links.  Let's fix them
Replace broken links with valid links
Checklist
> Docs - fix broken links

- docker/README.md
- docs/custom-plugins.md
- helm/fiftyone-teams-app/README.md
Instead of submitting suggestions to https://github.com/voxel51/fiftyone-teams-app-deploy/pull/110, I figured I would contribute.
Slight copy edits.
Checklist
> docs: minor edits to customer images.

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Let's take what topher created and give it a bit of polish.
* Copy editing
Checklist
n/a
* https://github.com/voxel51/fiftyone-teams-app-deploy/pull/112
> Copy edits for Updated Upgrade Notes for v1.6.0 and CAS

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Reviewed docs again for v1.6.0 release. Noticed a couple of things that could be cleaned up
* nested list
* whitespace
* example
Checklist
> docs: minor edits (deduplication, white space, fix example)

- docker/README.md
- helm/README.md
- helm/docs/expose-teams-api.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Woops!  Look like we didn't update all of the docs for v1.6.0 and path-based routing.  Let's fix that.
* docs
* more notes about path based routing and the new route for CAS
Checklist
> [AS-157] v1.6.0 path based routing docs

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
#141 has some formatting inconsistencies:
* white space
* line breaks
* code formatting
Instead of making suggestions that topher wouldn't be able to batch, let's try a PR to his PR branch.
As I previously reformatted the docs, each new sentence begins on a new line.
I'm also not aware of any pre-commit issues with the line lengths that lead to all the changes in #141. I'm curious to know/see what happened here.
* Whitespace
Checklist
<details>
<summary>pre-commit</summary>
```txt
[fiftyone-teams-app-deploy]$ git commit -m 'docs: formatting, spacing and line breaks.'
check for added large files..........................................................Passed
check for case conflicts.............................................................Passed
check that scripts with shebangs are …
```
> docs: formatting, spacing and line breaks.

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Just trolling through the docs, found some things that I think should be updated
- Add header Consistency between Helm `Upgrading from Previous Versions` and docker
- Add a new section for upgrading from v1.6.0 to v1.7.0 (which is easier)
- Some line-wrapping that something somewhere didn't like - it's all shorter, so I'mma leave it
Checklist
> Some Docs Updates for v1.7.0

- .github/workflows/pre-commit.yaml
- .github/workflows/release.yml
- .pre-commit-config.yaml
Let's add PR check running pre-commit.  While here, let's also tidy up a bit.
* Add pre-commit hook for github actions.
* Add github action workflow to run pre-commit on pull requests.
* Update existing actions to latest versions.
Checklist
See the "checks" section below.
> Some checks haven’t completed yet
> 1 in progress check 
It is working?? :aww_yeah:
> Chore: GitHub Actions -  Add workflow to run pre-commit [AS-141]

- .editorconfig
- .pre-commit-config.yaml
- .tool-versions
- Makefile
- utils/get-image-versions.sh
For integration tests, we need to know what images tags to use.  Before a release, we may use internal images stores in our docker registry. So let's add a script to do that for us.
* Makefile
* Targets for "popular" of release version, dev and rc
* script wrapping gcloud cli commands to get the latest tag based on version and "segment"
Checklist
<details>
<summary>Makefile Example Usage</summary>
```
[fiftyone-teams-app-deploy]$ make get-image-versions
./utils/get-image-versions.sh "1.7.0"
fiftyone-app
fiftyone-teams-api
fiftyone-teams-app
fiftyone-teams-cas
[fiftyone-teams-app-deploy]$ make get-image-versions-dev
./utils/get-image-versions.sh "1.7.0" dev
fiftyone-app	v1.7.0.dev9
fiftyone-teams-api	v1.7.0.dev9
fiftyone-teams-app	v1.7.0-dev.9
fiftyone-teams-cas	v1.7.0-dev.1 …
```
> Add util for getting latest internal image versions [AS-176]

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
> Fix broken links to Custom Plugins doc

- .pre-commit-config.yaml
- Makefile
The infrastructure team has decided to move forward with conventional commits. Let's make it a standard with pre-commit hooks:
Good Commit:
```shell
$ git commit -m 'chore: Pre-commit hooks for conventional'
check for case conflicts.................................................Passed
check yaml...........................................(no files to check)Skipped
detect aws credentials...................................................Passed
mixed line ending........................................................Passed
pretty format json...................................(no files to check)Skipped
markdownlint.........................................(no files to check)Skipped
markdownlint-fix.....................................(no files to check)Skipped …
```
> AS-264 Pre-commit hooks for conventional commits #105

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
standardize DO docs b/w docker & helm.
fix a bad link
> docs(teams-do) move to top of docker readme features, fix a link

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- update readme's reflecting 2.2.0 changes
- update helm and docker readme docs regarding invitations and FIFTYONE_ENCRYPTION_KEY
Checklist
> Update readme's for CAS

- .github/workflows/pre-release-internal-env.yml
- .github/workflows/release.yml
Org secrets are easier to manage than repo secrets. And let use a token with less permissions (workflow dispatch access).
* refactor(workflows): replace `CROSS_REPOSITORY_TOKEN` with with fine grained org secret `WD_HCI_FG_PAT`.
Checklist
Will be tested on the next release.
> refactor(workflows): replace `CROSS_REPOSITORY_TOKEN` with fine grained org secret

- Makefile
- skaffold.yaml
While looking at the our hard coded version strings, noticed that our helm integration and skaffold versions have fallen behind. In preparation for the v2.2.0 release, let's 
Checklist
> Chore: fix make clean target and  fix hard coded versions

- CONTRIBUTING.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- tests/testing.md
This merges `main` -> `release/v2.2.0` to get rid of any conflicts. After that, we can go from `release/v2.2.0` -> `main`.
```
git merge -X ours main
```
Checklist
> Merge main -> release/v2.2.0

- .tool-versions
This repo uses yq. So let's add it and it's jq dependency to the .tool-versions.
* add yq and jq
n/a
n/a
> chore(asdf): add jq and yq.

- .github/workflows/pre-release-internal-env.yml
- helm/docs/upgrading.md
Adding a release note about init container additions.
Checklist
> chore: Init Container Docs

- helm/docs/expose-teams-api.md
We've seen customers have issues with WSS upgrades when using an Nginx ingress class. This PR aims to document where we have seen success with nginx classes.
Adds additional documentation to `expose-teams-api` regarding Nginx.
Checklist
> chore: Adding Nginx docs

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Adds docker blurb for parity.
Alphabetizes the TOC/sections.
Checklist
> chore: Alpha

- Makefile
I noticed a few typos in comments. let's fix 'em.
* Makefile
Checklist
> docs: fix spellings
