- docker/README.md
- helm/README.md
Adds recommendations regarding the use of `FIFTYONE_DATABASE_ADMIN` during dockerized installs and upgrades.
> adds install and upgrade recommendations for docker

- docker/Dockerfile
I know, it really doesn't seem like a lot, but it's almost 20%
-The recommended Dockerfile now uses a multi-build approach and uses the python:3.10-slim-buster image as the base image.
- New build time is 106s compared to 160.1s using the old Dockerfile.
- New container installs fiftyone-teams-app in a virtual-environment.
- New container runs fiftyone-teams-app as the `voxel51` users instead of running as root.
The container built with this image has been deployed to voxel51.dev.fiftyone.ai running fiftyone-teams-app v0.2.2.
> Reduces fiftyone-teams-app image from 2.0GB to 1.6GB

- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/templates/api-service.yaml
- helm/fiftyone-teams-app/templates/app-service.yaml
- helm/fiftyone-teams-app/templates/teams-app-service.yaml
Services of type NodePort allow for a `nodePort` to be set to handle loadbalancing.
This change allows the addition of a `nodePort` parameter when the Service Type is `NodePort`
Rendering with ClusterIP:
```
---
apiVersion: v1
kind: Service
metadata:
name: teams-api
namespace: staging-fiftyone-ai
labels:
helm.sh/chart: fiftyone-teams-app-1.1.2-beta2
app.kubernetes.io/version: "v1.1.1"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: teams-api
app.kubernetes.io/instance: fiftyone-teams-app
spec:
type: ClusterIP
ports:
- port: 1234
targetPort: 8000
protocol: TCP
name: http
selector:
app.kubernetes.io/name: teams-api
app.kubernetes.io/instance: fiftyone-teams-app
```
Rendering ClusterIP with `nodePort` set (invalid configuration):
```
❯ grep -B1 -A1 nodePort staging-values.yaml …
```
> adds nodeport support for NodePort Services

- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/api-service.yaml
- helm/fiftyone-teams-app/templates/ingress.yaml
- helm/fiftyone-teams-app/values.yaml
We need to expose the API service in the future for SDK access; this provides an opportunity for that.
Existing values.yaml files render with a null diff.
values.yaml files with `ingress.paths` defined render using the old mechanism for backwards compatibility.
> Adds an option for adding the API service to the Ingress Controller

- docker/README.md
- docker/compose.dedicated-plugins.yaml
- docker/compose.plugins.yaml
- docker/compose.yaml
- helm/README.md
- helm/docs/expose-teams-api.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/values.yaml
```
❯ ack -l '0.13.1'
❯ ack -l '0.21.1'
❯ ack -l '1.3.1'
```
bumping version numbers in preparation for a 1.3.2 release
> updates for 1.3.2 release

- docker/README.md
- docker/compose.dedicated-plugins.yaml
- docker/compose.plugins.yaml
- docker/compose.yaml
- helm/README.md
- helm/docs/expose-teams-api.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/values.yaml
bumping helm and docker compose versions, bumping versions in documentation
```
❯ ack -l '0.13.2'
❯ ack -l '1.3.2'
❯ ack -l '0.21.2'
❯
```
> updates for Teams v1.3.3

- docker/README.md
- helm/README.md
A number of documentation clarifications have been made over in `release/v1.5.0` but would be useful over here
This PR brings those changes over for the FiftyOne Teams 1.4.2 release on Friday Morning.
> Cherry-pick `release/v1.5.0` doc updates into `release/v1.4.2`

- .github/workflows/release.yml
- docker/README.md
- docker/compose.dedicated-plugins.yaml
- docker/compose.plugins.yaml
- docker/compose.yaml
- helm/README.md
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
FiftyOne Teams 1.4.2 is coming; this change bumps the versions in the docs for that release.
> bump versions in prep for release

- .github/workflows/release.yml
The action doesn't trigger on a change to the workflow; this will allow us to trigger it manually when necessary.  The job won't update the release if there haven't been changes.
> trigger manually

- .github/workflows/release.yml
[version 1.4.2](https://github.com/voxel51/fiftyone-teams-app-deploy/actions/runs/6435492179/job/17476869347) of the helm-chart releaser is no longer available.
Bumping to the latest release
> version 1.4.2 is no longer available

- .github/workflows/release.yml
Moving too fast with too many balls in the air...
helm/chart-releaser-action is at version [v1.5.0](https://github.com/helm/chart-releaser-action)
we don't need the manual trigger, it runs when the workflow is actually merged.
> version 1.5.0 not 1.6.0

- docker/README.md
- helm/README.md
We do want this to go against `main` so that it is released immediately
> correct DB version

- helm/docs/expose-teams-api.md
On my first pass through the docs, I made a mental note to revisit the document around the FiftyOne Teams API.  This came up during a discussion with a customer and since it was top of mind, thought I would take a moment to improve the docs.
> Improve docs around exposing the FiftyOne Teams API in kubernetes.

- CONTRIBUTING.md
- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Adds documentation for snapshot archive feature.
Mostly points to the official documentation [here](https://docs.voxel51.com/teams/dataset_versioning.html#dataset-versioning-configuration), however goes into a little bit more technical detail given the audience specifically needs to deploy these variables.
So I based the text off of the plugins section and tried to adapt it as best I could.
> Snaphot Archive Feature Documentation

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
We just had a conversation with a customer who was running into issues when they enabled `teams-plugins`
This was due to the fact that they hadn't added `teams-plugins` to their `no_proxy` configuration
This change adds guidance to help with this configuration change in the future.
> add more details around `teams-plugins` no_proxy

- .pre-commit-config.yaml
- docker/README.md
- helm/README.md
someone did a neat thing and added a TOC to helm.fiftyone.ai
This extends that work and adds a TOC to the `README.md` files in the top-level of the `fiftyone-teams-app-deploy/helm` and `fiftyone-teams-app-deploy/docker` directories.
> add TOC to docker and helm README too

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/values.yaml
I, mistakenly, put this in the wrong set of env vars, and we all missed it during the review (all of the helm-chart output said it was wrong... 🤷 )
I got the docker part right, so no changes needed there.
Also, I botched the docs...
<details>
<summary>Helm Update with no overrides</summary>
```
❯ helm diff -C1 upgrade demo-fiftyone-ai ../fiftyone-teams-app-deploy/helm/fiftyone-teams-app -f helm-configs/demo-values.yaml
demo-fiftyone-ai, teams-app, Deployment (apps) has changed:
...
key: cookieSecret
+             - name: FIFTYONE_API_URI
+               value: https://demo-api.fiftyone.ai
- name: FIFTYONE_SERVER_ADDRESS
...
```
</details>
<details>
<summary>Helm Update with no `apiSettings.dnsName`</summary>
```
❯ helm diff -C1 upgrade demo-fiftyone-ai …
```
> `FIFTYONE_API_URI` belongs on `teams-app` not `fiftyone-app`

- docker/example-nginx-api.conf
- docker/example-nginx-path-routing.conf
Motivation: default body max is 1M for nginx. Add explicitly to the example so it's higher for API connections, and so customers can know to override if they wish.
The headaches you'll run into by having a lower max body size are greater than the possibility of getting DoS'ed by huge requests, in my opinion.
Besides, the Sanic max request size is 100M so it makes sense to be consistent.
> Increase client_max_body_size in nginx example

- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
bump:
Teams Version `1.5.3`->`1.5.4`
`fiftyone` version `0.15.3`->`0.15.4`
OSS (aka database) version `0.23.2`->`0.23.3`
> Bump version numbers in prep for v1.5.4 release

- .pre-commit-config.yaml
Since this repo is a boilerplate for installation, it may contain secret information that we do not want to add to this public repository.
To prevent that, I added a new pre-commit hook https://github.com/Yelp/detect-secrets.  It takes a while to run, but the commit runtime tradeoff is preferable to commiting secrets.
* Added pre-commit hook `detect-secrets`
After installing the hook via `make hooks`, we can run this one hook against the repo
```shell
[fiftyone-teams-app-deploy]$ time pre-commit run detect-secrets --all-files
Detect secrets...........................................................Passed
pre-commit run detect-secrets --all-files  21.80s user 0.46s system 108% cpu 20.576 total
```
> Add pre commit hook detect secrets

- .pre-commit-config.yaml
- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
- helm/gke-example/values.yaml
- helm/values.yaml
Bump release versions for release later today
```
16545  for file in $(find ./ -type f -exec grep -il '0.15' {} \;); do perl -pi -e 's/0\.15\.4/0.15.5/g' $file; done
16546  for file in $(find ./ -type f -exec grep -il '0.23' {} \;); do perl -pi -e 's/0\.23\.3/0.23.4/g' $file; done
16547  for file in $(find ./ -type f -exec grep -il '1.5' {} \;); do perl -pi -e 's/1\.5\.4/1.5.5/g' $file; done
```
Will be used for test release.fiftyone.ai deploys later today, post merge
> bump release versions (prep for release later today)

- .pre-commit-config.yaml
- .tool-versions
- CONTRIBUTING.md
- Makefile
- helm/docs/expose-teams-api.md
- helm/gke-example/values.yaml
- helm/local-self-signed-example/README.md
- helm/local-self-signed-example/cert-manger-crds/README.md
- helm/local-self-signed-example/cert-manger-crds/crd-certificaterequests.yaml
- helm/local-self-signed-example/cert-manger-crds/crd-certificates.yaml
- helm/local-self-signed-example/cert-manger-crds/crd-challenges.yaml
- helm/local-self-signed-example/cert-manger-crds/crd-clusterissuers.yaml
- helm/local-self-signed-example/cert-manger-crds/crd-issuers.yaml
- helm/local-self-signed-example/cert-manger-crds/crd-orders.yaml
- helm/local-self-signed-example/cluster-issuer.yaml
- skaffold-cert-manager.yaml
- skaffold-mongodb.yaml
- skaffold.yaml
Being able to run the the app locally allows us to manually test our Helm Chart.  It also allows us to run the system locally, in minikube to be able to manually validate the app or changes to our helm charts.
This PR adds initial minikube and skaffold configurations (and some helpers).  The updated CONTRIBUTING.md contains the steps to getting this running.
Consider this an initial proof of concept (POC).
Added
* minikube
* skaffold
* cert-manager (for self-signed certificates)
* mongodb
1. Auth with gcloud
```shell
gcloud auth application-default login
```
1. Install the asdf tools
```shell
make asdf
```
1. In one terminal, start minikube
```shell
make start
```
1. In another terminal, run skaffold
```shell
skaffold dev --keep-running-on-failure
```
1. In another terminal, run minikube …
> Enable local chart development through skaffold and minikube

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/values.yaml
Based on the documentation [here](https://docs.google.com/document/d/1aNuQGPHz3pKCVU7Zd17UDAVJN9kYqGVRGWSm4WlCwWM/edit#heading=h.k6nuqv7tv8sz) we need to update the CAS environment variables for 'no-legacy' (newauth.dev.fiftyone.ai) deployments
This is all still in the scope of `release/v1.6.0` so there is time to adjust this (and I'm sure there will be more changes) but this PR is to give a first look at the changes to discuss alternative perspectives on how best to introduce these changes.
Refactoring the helm chart to:
- omit Auth0 configurations when `no-legacy` mode is in use
- add defaults for the new CAS environment variables, where appropriate
- add new CAS environment variables to the CAS deployment
Tested with the `voxel51/cloud-build-and-deploy:topher/cas-no-legacy-helm-chart` …
> Add new configuration for CAS "no legacy" mode

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/values.yaml
Refactoring the helm chart to understand `FIFTYONE_AUTH_MODE` instead of `ENABLE_LEGACY_MODE`
Changes `ENABLE_LEGACY_MODE: (true|false)` to `FIFTYONE_AUTH_MODE: "(internal|legacy)"`
<details>
<summary> `FIFTYONE_AUTH_MODE: "internal"` </summary>
```
❯ export _K8S_ENVIRONMENT='newauth-dev'
export FTA_VERSION='1.6.0rc1+e5d4b9b'
export FOT_VERSION='1.6.0rc1+9d97347'
export APP_VERSION='v1.6.0-e5d4b9b.0'
export CAS_VERSION='v1.0.1-e5d4b9b.0'
export FO_VERSION='0.16.0rc1+9d97347'
helm diff -C1 upgrade ${_K8S_ENVIRONMENT}-fiftyone-ai ../fiftyone-teams-app-deploy/cas-auth-mode-refactor/helm/fiftyone-teams-app -f helm-configs/${_K8S_ENVIRONMENT}-values.yaml --namespace ${_K8S_ENVIRONMENT}-fiftyone-ai --set apiSettings.env.FIFTYONE_TEAMS_VERSION_OVERRIDE="api v${FTA_VERSION} / app v${FOT_VERSION} …
```
> refactor FIFTYONE_AUTH_MODE

- helm/values.yaml
topher suggest smart things. Let's do it.  To assist customers in successful installations, let's set sane default value in the stub template we provide them.  The initial installation requires that `appSettings.env.FIFTYONE_DATABASE_ADMIN=true`.  Failure to set this will cause an error.
After the initial installation, the customer should set this to false to avoid sdk compatibility issues later.
In our values.yaml template for customers, uncomment the `appSettings` section.
> docs - uncomment appSettings for inital install.

- docker/internal-auth/common-services.yaml
- docker/internal-auth/compose.dedicated-plugins.yaml
- docker/internal-auth/compose.plugins.yaml
- docker/internal-auth/env.template
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/values.yaml
Updates from Developers in the [CAS Deployment](https://docs.google.com/document/d/1aNuQGPHz3pKCVU7Zd17UDAVJN9kYqGVRGWSm4WlCwWM/edit#heading=h.k6nuqv7tv8sz) documentation requires updates to our deployment artifacts.
Update Helm Chart to reflect new env var requirements
Update Docker Compose `internal-auth` configurations to reflect new env var requirements
Some alphabetization, where reasonable
<details>
<summary> `internal` auth mode test </summary>
```
❯ export _K8S_ENVIRONMENT='newauth-dev'
export FTA_VERSION='1.6.0rc2+2be7b3d'
export FOT_VERSION='1.6.0rc2+c8939b3'
export APP_VERSION='v1.6.0-2be7b3d.0'
export CAS_VERSION='v1.0.1-2be7b3d.0'
export FO_VERSION='0.16.0rc2+c8939b3'
helm diff -C1 upgrade ${_K8S_ENVIRONMENT}-fiftyone-ai …
```
> More CAS Env Var Updates

- tests/unit/api-deployment_test.go
- tests/unit/api-service_test.go
- tests/unit/app-deployment_test.go
- tests/unit/app-hpa_test.go
- tests/unit/app-service_test.go
- tests/unit/ingress_test.go
- tests/unit/plugins-deployment_test.go
- tests/unit/plugins-hpa_test.go
- tests/unit/plugins-service_test.go
- tests/unit/teams-app-deployment_test.go
- tests/unit/teams-app-hpa_test.go
- tests/unit/teams-app-service_test.go
While reviewing the newly added helm unit tests, we realized that failures in DeepEquals weren't showing the diffs (of expected vs actual).  The testify library already supports this using the https://pkg.go.dev/github.com/stretchr/testify/assert#Equal.  Let's replace the calls to `s.True(reflect.DeepEqual(...))` with `s.Equal(...)`.
While running the tests, noticed failed tests in `tests/unit/teams-app-deployment_test.go` that expected the old chart version.
* Update assertions
* Change version number from `0.15.6` to `0.15.7`.
<details>
<summary>Passing Helm Unit Tests</summary>
```
$ make test-unit-helm
=== RUN   TestDeploymentApiTemplate
=== PAUSE TestDeploymentApiTemplate
...
--- PASS: TestDeploymentPluginsTemplate/TestVolumes/defaultValues (0.30s)
PASS
ok …
```
> Helm Unit Tests - Show diff when objects are not equal

- .github/pull_request_template.md
To err is human. However, let's reduce the drift in changes between Docker Compose and Helm. To help, let's add a checkbox to the PR template to remind us maintaining parity with the changes we introduce.
- Updated PR template
Checklist
This PR
> Update PR template to remind of parity between Docker Compose and Helm [AS-103]

- docker/README.md
- helm/fiftyone-teams-app/README.md
A customer recently reported an error while running the db migration.  Let's take this opportunity to express that for a new installation, when the configuration is set to initialize the database on first run, that this step may not be necessary.
* Docker Compose Docs
Checklist
> Docs - Compose DB Migration

- docker/docs/expose-teams-api.md
While looking at the links in the docker directory, this one is broken.  Let's help it out.
* Add an extra dot to find the link
Checklist
n/a ^
link now takes to the intended page
> docs: in docker docs, fix brokenlink to teams plugins doc

- CONTRIBUTING.md
- Makefile
- skaffold.yaml
Since v1.5.5 release, we haven't incremented the chart version in `skaffold.yaml`. Let's fix that.  It's ok for time being that the skaffold config file won't include v1.6.0 as we cannot yet build container images for arm64.
While here, let's make sure that we are authenticating with the proper gcloud project.  Failure to use the right one results in access errors to the internal container images.
* `skaffold.yaml`
* bump fityone-teams-app chart version from `v1.5.5` to `v1.5.8`
* `makefile`
* add target `auth` with `--project` argument
* `CONTRIBUTING.md`
* update to use `make auth` 
Checklist
n/a ^
Use new commands and configurations to run v1.5.8 locally, successfully.
> In skaffold.yaml, bump chart version from 1.5.5 to 1.5.8.

- docker/README.md
- docker/internal-auth/env.template
- helm/fiftyone-teams-app/README.md
During a recent customer installation, the customer provided feedback that they didn't know what variables should be set.  Let's try to make this a bit more explicit.
* compose
* reword add clarity around the required
* noticed that in our refactor for internal mode, we didn't replace ref to a renamed var (`AUTH0_BASE_URL` to `BASE_URL`)
* helm
* enumerate the "required" variables
Checklist
> Update instructions around the required settings for helm and compose

- docker/README.md
- docs/custom-plugins.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Got a Slack Message [from a customer](https://voxel51.slack.com/archives/C06QD55JFGC/p1712231912862079) asking for more information about building/using custom plugins images.
The links in the documents may not actually work until this is published.
Add an example dockerfile and configuration parameters.  Entirely documentation-based.
Checklist
Built `local-image/fiftyone-app-tophertest:v1.5.8` locally
> adds some documentation around custom plugins images

- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/gke-example/values.yaml
- tests/unit/compose/docker-compose_test.go
In #115, I accidentally forgot replace the version strings `v1.5.8` with `v1.5.9`.
Replace `v1.5.8` with `v1.5.9`.
Checklist
> chore: forgot to bump v1.5.8 to v1.5.9 for the release.

- docker/README.md
- docker/common-services.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/gke-example/values.yaml
- tests/unit/compose/docker-compose_test.go
Reverts voxel51/fiftyone-teams-app-deploy#116 after errors found after deploying to staging and verifying the app.
> Revert "chore: forgot to bump v1.5.8 to v1.5.9 for the release."

- docker/common-services.yaml
- helm/gke-example/values.yaml
- tests/unit/compose/docker-compose_test.go
during the v1.5.10 release, I hadn't noticed that the grep regex matching the word didn't update v1.5.9 to v1.5.10.  Since, I updated our docs to include a grep regex pattern that would match this.  Used it to create the changes in this pr. 
* change "v1.5.9" to "v1.5.10" which was not changed during the release due to not matching the regex.
Checklist
unit tests pass for compose and helm pass.
`1.5.9` no longer exists in the repo:
```shell
[fiftyone-teams-app-deploy]$ grep -r '1\.5\.9' . --exclude-dir=.git
```
and `1.5.10` does:
```shell
[fiftyone-teams-app-deploy]$ grep -r '1\.5\.10' . --exclude-dir=.git
./docker/README.md:    image: voxel51/fiftyone-app-torch:v1.5.10
./docker/README.md:1. [Upgrade to FiftyOne Teams version 1.5.10](#deploying-fiftyone-teams)
./docker/README.md:You will …
```
> Change v1.5.9 to v1.5.10

- .gitignore
- .pre-commit-config.yaml
- Makefile
- tests/fixtures/docker/compose.override.darwin.yaml
- tests/fixtures/docker/compose.override.yaml
- tests/fixtures/docker/integration_internal_auth.env
- tests/fixtures/docker/integration_legacy_auth.env
- tests/go.mod
- tests/go.sum
- tests/integration/compose/common_test.go
- tests/integration/compose/docker-compose-internal-auth_test.go
- tests/integration/compose/docker-compose-legacy-auth_test.go
Let's add some integration tests for Docker Compose. (Helm integration tests will come in a future PR).  These check that the containers can run via docker compose in both authentication modes (legacy and internal).
This includes docker compose configurations for runnning a mongodb for the integration tests. For now, keeping at MVP (with iterative improvements), I disabled the parallelization.  In order to support parallel execution of the tests, we would need to add sophistication to the mongodb service to use a parameterized port for mongodb and dynimcally create that for each test and test case run.  In serial, the tests run in ~25 seconds. Let's not pre-maturely optimize.
For the tests, we validate that the service container started.  Then, chech the service container logs for known …
> [AS-107] Add Integration Tests for Docker Compose

- docker/README.md
Ran into two things that weren't completely clear when attempting to upgrade.
Adds:
* A note in the v1.1.0 -> v1.6.0 upgrade section about the additional `.env` variables that may have been overwritten if just copying the `.env` file to the `legacy-auth` directory.
* A note in the CAS section about needing to configure path based routing if applicable
Checklist
> Clarify Docker CAS changes

- docker/README.md
Testing upgrade to v1.6 (legacy mode)
Minor updates
Checklist
* (not sure, only editing compose) This PR maintains parity between Docker Compose and Helm
Upgrade allen.dev.fiftyone.ai internal environment to v1.6 (legacy mode, docker-compose)
>  Minor updates v1.6 docker-compose deploy docs

- docker/common-services.yaml
[This Slack thread](https://voxel51.slack.com/archives/C03Q2JMQNGK/p1714402912327019?thread_ts=1713896144.558929&cid=C03Q2JMQNGK) suggests that we should set CAS defaults so customers don't have to keep up to date with current environment variables in docker-compose.
Seems fine to me.
Sets some defaults for CAS environment variables in docker-compose common services
Checklist
No, but Helm already had those settings
Remove the CAS configs you don't need:
```
$ diff -uw .env cas.env
--- .env        2024-04-30 11:37:23.293987356 +0000
+++ cas.env     2024-04-30 11:30:12.402909497 +0000
@@ -60,16 +60,16 @@
APP_BIND_PORT=3500
-# CAS_BASE_URL=http://teams-cas:3000/cas/api
-# CAS_BIND_ADDRESS=127.0.0.1
+CAS_BASE_URL=http://teams-cas:3000/cas/api
+CAS_BIND_ADDRESS=127.0.0.1
CAS_BIND_PORT=3530 …
```
> let`s try some cas defaults for docker

- .pre-commit-config.yaml
- Makefile
- helm/fiftyone-teams-app/README.md.gotmpl
- skaffold.yaml
- tests/fixtures/helm/integration_values.yaml
- tests/integration/compose/docker-compose-internal-auth_test.go
- tests/integration/compose/docker-compose-legacy-auth_test.go
- tests/integration/helm/common_test.go
- tests/integration/helm/helm-internal-auth_test.go
- tests/integration/helm/helm-legacy-auth_test.go
- tests/testing.md
As promised in #113, here is the addition of integration tests for Helm.  These check that the containers can run via docker compose in both authentication modes (legacy and internal).
This includes Helm configurations for running a mongodb for the integration tests. For now, keeping at MVP (with iterative improvements), I disabled the parallelization. In order to support parallel execution of the tests, we would need to add sophistication to the mongodb installation to use a parameterized port for mongodb and dynamically create that for each test and test case run. In serial, each tests run in 1 minute.
For the tests, we validate that the service container started. Then, check the service container logs for known working output. Then, if the service supports it, run an http check on an …
> Add Integration Tests for Helm [AS-105]

- docker/README.md
- helm/docs/expose-teams-api.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- skaffold.yaml
- tests/fixtures/helm/integration_values.yaml
Today, we learned that ordering for routing rules matter.  Let's instruct users to add the `/cas` rule before the `/` rule.  
* Docs
* compose 
* helm 
Checklist
> docs: `/cas` routing rule - ordering matters [AS-166]

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Often, during customer engagements, we have to describe the three plugin modes for Fiftyone Teams.  Let's add that to our deployment docs, so customers have access to the information during the installation phase.
* Docs
* Add information about the three plugin modes and supporting information that can inform customer behanvior
Checklist
> docs: Add additional information for plugin modes in Docker compose and Helm [AS-102]

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
In [#138 ](https://github.com/voxel51/fiftyone-teams-app-deploy/commit/d6493bfe376a8b41d3137ac1f60b6dc51d8dcaf9) I experimented with reducing our `initialDelaySeconds` from `45` to `15`.  It lead to a startup time reduction from speed 232s to 154s in my skaffold/minikube environment.
* `initialDelaySeconds` from `45` to `15`
Checklist
No ^. This is a Helm only change.
This was validated during the the development of our Helm integration tests and its runs.
* #144 - closed in favor of this PR whose base branch is `release/v1.7.0` (instead of main)
> feat: in Helm chart, reduce the `initialDelaySeconds` from `45` to `15` [AS-70]

- .github/dependabot.yml
Since we use GitHub Actions, let's enable dependabot alerts for action updates.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* added .github/dependabot.yml
* set `package-ecosystem` to "github-actions"
Checklist
n/a ^
Will be performed in the future
> Add dependabot github actions

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
The changes in this PR involve updates to the documentation for FiftyOne Teams v1.6.0 and above. Specifically, it addresses a known issue related to the Central Authentication Service (CAS) and the incomplete instructions for installing FiftyOne.
The issue arises because metadata previously provided by Auth0 is no longer available, resulting in the absence of the Voxel51 PyPI token in the installation instructions. To resolve this, users can override the installation instructions by setting the `FIFTYONE_APP_INSTALL_FIFTYONE_OVERRIDE` environment value.
The PR provides detailed instructions on how to set this environment value in both Docker Compose and Helm deployments. It also includes information on obtaining the PyPI token from the Customer Success representative.
In summary, this PR …
> Document `FIFTYONE_APP_INSTALL_FIFTYONE_OVERRIDE`

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Not sure where that other link came from, but I did a great job of putting the same weird link everywhere!
fixes legacy-auth-mode link
Checklist
> Fix `legacy-auth-mode` link in documentation

- Makefile
- skaffold.yaml
In #136, I tried to update skaffold for v1.6.1 but encountered app errors that have since been fixed.  So let's try this again.
* skaffold
* Update chart version for 1.7.1
* Change image tags to 1.7.1 to rc builds
* Remove setting the service probes (since those are now chart defaults)
* Makefile
* Add `--kube-context` to skaffold commands to avoid deploying to the users current kubernetes context
Checklist
No! This is Helm only.
1. Deploy the app to k8s
```shell
make delete start dev-keep
```
1. Start a minikube tunnel, in another terminal 
```shell
sudo minikube tunnel
```
1. Navigate to https://local.fiftyone.ai and login
1. Get redirected to the datasets page 
See? No infinite redirects!!
* #136
> [AS-143] skaffold v1.7.1

- .github/workflows/test-docker.yml
Like #157 created by dependabot, but, hopefully the pr checks tests will pass.
Bumps [docker/login-action](https://github.com/docker/login-action) from 3.1.0 to 3.2.0.
- [Release notes](https://github.com/docker/login-action/releases)
- [Commits](https://github.com/docker/login-action/compare/v3.1.0...v3.2.0)
---
- dependency-name: docker/login-action dependency-type: direct:production update-type: version-update:semver-minor ...
Checklist
> chore(deps): bump docker/login-action from 3.1.0 to 3.2.0

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Attempting to be more precise and practically relevant in describing SDK/DB compatibility and upgrade instructions.
- When upgrading from v1.6.0 or later to v1.7.1, the DB compatibility version is not changing; so SDK upgrades are optional. 
- When upgrading from v1.6.0 or later to v1.7.1, DB/dataset migrations are also optional.
- Specify correct lower-bound SDK version (0.17.0) below which connectivity will be lost with DB compatibility version 0.24.0 
Checklist
> SDK/Database update instructions for upgrading to v1.7.1 from v1.6.0 or later

- .github/workflows/pre-commit.yml
- .github/workflows/release.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
dependabot opened #167, but the PR checks don't run.  After cherry picking the commit into this branch, the PR checks will run.
Bumps [actions/checkout](https://github.com/actions/checkout) from 4.1.6 to 4.1.7.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v4.1.6...v4.1.7)
---
- dependency-name: actions/checkout dependency-type: direct:production update-type: version-update:semver-patch ...
* GitHub Action checkout upgrade from v4.1.6 to v4.1.7
This PR's checks
Like https://github.com/voxel51/fiftyone-teams-app-deploy/pull/167 but this will allow the PR checks to run.
> chore(deps): bump actions/checkout from 4.1.6 to 4.1.7

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
`serverPathPrefix` was never actually plumbed into our helpers, and isn't configurable in the context of Teams.
This just removes the unused configuration parameter (and associated TODO) from the `values.yaml` (which also updates the docs)
removes unused `teamsAppSettings.serverPathPrefix`
Checklist
PR testing below, searched for instances of `serverPathPrefix` after change and none found
> serverPathPrefix isn`t used and isn`t useful

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
bumps actions/setup-python from 5.1.0 to 5.1.1
This is a replacement for [PR 172](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/172) to allow integration tests to run
bumps actions/setup-python from 5.1.0 to 5.1.1
Checklist
GitHub Actions running on this PR
> chore(deps): bump actions/setup-python from 5.1.0 to 5.1.1

- docker/README.md
- docker/legacy-auth/env.template
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
A customer encountered redirect URL mismatch when upgrading their second deployment (using the same database host/instance).  In this scenario, the second deployment used the same CAS database.  The resolution was to set a unique value for `CAS_DATABASE_NAME` for the second deployment.  Let's document this
* Add notes about colocating multiple deployments on the same database host requires setting unique values for `CAS_DATABASE_NAME`
Checklist
N/A - Docs only update.
> Docs: Add notes for CAS Database name uniqueness for multiple depoyments using same database host

- .github/workflows/test-docker.yml
Same as https://github.com/voxel51/fiftyone-teams-app-deploy/pull/175 but not a dependabot fork to allow PR checks to run.
Bumps [docker/login-action](https://github.com/docker/login-action) from 3.2.0 to 3.3.0.
- [Release notes](https://github.com/docker/login-action/releases)
- [Commits](https://github.com/docker/login-action/compare/v3.2.0...v3.3.0)
---
- dependency-name: docker/login-action dependency-type: direct:production update-type: version-update:semver-minor ...
> chore(deps): bump docker/login-action from 3.2.0 to 3.3.0

- Makefile
- docker/README.md
- docker/common-services.yaml
- docker/internal-auth/env.template
- docker/legacy-auth/env.template
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/cas-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- helm/values.yaml
- tests/fixtures/docker/compose.override.mongodb.yaml
- tests/fixtures/docker/integration_internal_auth.env
- tests/fixtures/docker/integration_legacy_auth.env
- tests/integration/compose/docker-compose-internal-auth_test.go
- tests/integration/compose/docker-compose-legacy-auth_test.go
- tests/unit/compose/docker-compose-internal-auth_test.go
- tests/unit/compose/docker-compose-legacy-auth_test.go
- tests/unit/helm/cas-deployment_test.go
For release v2.0.0 we only support a single organization, but in the future there may be multiple organizations which require multiple license files.
Rather than release one mechanism for a single license file and make everybody change over later, this PR sets us up for multiple license files in the future.
- Refactor mongodb integration-compose tests to use a volume that is destroyed on `down`
-   I was getting failures because `/tmp/mongodb` had corrupted database files in it
- Refactor helm chart to take a list of secret names and create a `LICENSE_KEY_FILE_PATHS` env var
- Refactor compose to mount a directory and require a `LICENSE_KEY_FILE_PATHS` env var
- Update documentation without reference to multiple license files as it's not yet supported
Checklist
[release …
> In the future there may be multiple license files

- .pre-commit-config.yaml
- Makefile
- tests/go.mod
- tests/integration/helm/common_test.go
- tests/integration/helm/helm-internal-auth_test.go
- tests/integration/helm/helm-legacy-auth_test.go
- tests/testing.md
- tests/unit/helm/cas-deployment_test.go
Like #178, but addresses all of @findtopher's PR comments.  For details, see the description of that PR.
* In addition, finished replacement of `licencefile` to `license-file`
Checklist
```shell
$ make test-integration-helm
=== RUN   TestHelmInternalAuth
=== PAUSE TestHelmInternalAuth
=== CONT  TestHelmInternalAuth
=== RUN   TestHelmInternalAuth/TestHelmInstall
=== RUN   TestHelmInternalAuth/TestHelmInstall/builtinPlugins
...
--- PASS: TestHelmInternalAuth (383.09s)
--- PASS: TestHelmInternalAuth/TestHelmInstall (383.09s)
--- PASS: TestHelmInternalAuth/TestHelmInstall/builtinPlugins (182.95s)
--- PASS: TestHelmInternalAuth/TestHelmInstall/sharedPlugins (105.86s)
--- PASS: TestHelmInternalAuth/TestHelmInstall/dedicatedPlugins (94.28s)
PASS
ok …
```
> test: update helm integration test to dynamically create licensefile (retry) [AS-215]

- .github/workflows/test-docker.yml
Like #183, but performed by human to trigger PR checks
See #183 
Checklist
After this PR passes checks and merges, I will close #183
> chore(deps): bump google-github-actions/auth from 2.1.3 to 2.1.5

- docker/common-services.yaml
- docker/legacy-auth/compose.dedicated-plugins.yaml
- docker/legacy-auth/compose.plugins.yaml
- docker/legacy-auth/compose.yaml
- helm/fiftyone-teams-app/templates/_helpers.tpl
- tests/unit/compose/docker-compose-internal-auth_test.go
- tests/unit/helm/cas-deployment_test.go
`TEAMS_API_DATABASE_NAME` is required in `internal` mode now -  [PR 1443](https://github.com/voxel51/voxel-hub/pull/1443/files)
remove the `if legacy` clause around the env vars
Checklist
unit tests - compose tests
> `TEAMS_API_DATABASE_NAME` is required

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
helm.fiftyone.ai links don't seem to render markdown for local files - use the github links instead
replace the link with the github link
Checklist
not a really good way to test this, but the existing github link seems to work fine
> use the github link for plugins-storage

- CONTRIBUTING.md
- Makefile
- tests/testing.md
While working with a colleague today, I noticed that when we refactored the tests for license file, we didn't update the tests/testing.md to include the license file steps.
While here, added some extra notes for speeding up the runs by preloading cert-manager and MongoDB.
And added make dependencies for helm integration tests to download the license secrets (so there be less commands for us to manually run). (these dependencies already existed for Docker).
If we don't want to include this in the 2.1.1 release, we can target for the next release.
* docs
* testing.md
* contributing.md
* Makefile 
Checklist
> docs: license file for testing and make helpers

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
We should document how [GKE Workload Identity Federation](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity) is achieved in FiftyoneTeams. This PR aims to add a new section to the helm chart's README, adding GKE-centric deployment steps.
Closing [this PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/214) in favor of this new one because of conflicts and unexpected diffs.
New links, docs, and write-ups pertaining to GKE workload identity.
Checklist
> chore: Branching off of 2.2.0 because of conflicts

- skaffold.yaml
We recently changed how we build our release container images.  Previuosly, these would not run on arm64.  After the change, they do.  Let's rev the versions in the release/v2.2.0 in preparation for our replacement commands so they get release with the `v2.2.0` tags.
* skaffold
* set tag versions to latest release
Checklist
No ^ This only affects the skaffold (Helm).
With these settings, was able to run the app locally without the containers erroring.
> fix(skaffold): set tag versions to latest release

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
It appears any installation of `gcloud` is missing from the docker-compose workflows. However, our makefile is requiring it.
Adding `gcloud` installation.
Updates `test-docker.yml` to include `setup-gcloud` action.
Checklist
> chore: Fixing google auth and logins

- .github/workflows/pre-release-internal-env.yml
Instead of forcing internal cloud-builds to publish charts on requests, we should just build/publish them on pushes to this repository for non-main branches. This PR builds the fiftyone teams helm chart and dependent charts in an automated fashion.
Additional GitHub action to:
1. Update any versions
2. Package helm chart
3. Push to internal registry
4. Update dependent repositories via triggers
Checklist
[GitHub actions](https://github.com/voxel51/helm-charts-internal/actions/runs/11439938801)
> AS-289 Continuous Chart Publishing

- .github/workflows/pre-release-internal-env.yml
In a previous PR, we enabled continuous publishing of helm charts based on branches. The `GITHUB_BRANCH` environment variable is deprecated, switching to `GITHUB_REF_NAME` per [the docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)
Update conditional in GH actions.
Checklist
> Fixing GITHUB_REF_NAME environment variable

- .github/workflows/pre-commit.yml
- .github/workflows/pre-release-internal-env.yml
- .github/workflows/release.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Supersedes [this PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/227) and changes target to release branch.
See [this PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/227) for more information.
Checklist
> chore(deps): bump actions/checkout fro 4.2.x to 4.2.2

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Supersedes [this PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/226) and changes target to release branch.
See [this PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/226) for more information.
Checklist
> chore(deps): bump actions/setup-python from 5.2.0 to 5.3.0

- .github/workflows/release.yml
We use the fiftyone-teams-app chart as a subchart for our internal environments.  When we release a new version of fiftyone-teams-app, let's trigger the build of the internal environment chart.
I also created a new repo secret `CROSS_REPOSITORY_WORKFLOW_2`.
* wokflows
* release
* `azure/setup-helm@v4` no longer needs a token
* `Run chart-releaser`
* alpha sort 
* set id to be used in later job
* Add job `update-chart-version` that only runs when chart release publishes to trigger remote workflow in private repo
Checklist
No. This is a helm only change.
> chore(workflows): on chart release, trigger action in cross repository to build and publish [AS-281]

- .pre-commit-config.yaml
- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/templates/NOTES.txt
- helm/fiftyone-teams-app/templates/ingress.yaml
We should warn users who are using older kubernetes versions. For extremely old versions, like 1.18.0, we should add a hard "no install" rule by utilizing `kubeVersion`.
The soft deprecation notice will be shown when there is a version that is EOL ( older than 1.28).
Add `kubeVersion` to `Chart.yaml`. Have to include pre-release versions for google (see [this](https://github.com/helm/helm/issues/3810))
Checklist
`helm install --dry-run` against various versions of kube:
> AS-111 Adding Deprecation Notices

- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/ingress.yaml
- helm/fiftyone-teams-app/templates/serviceaccount.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-hpa.yaml
- helm/fiftyone-teams-app/templates/teams-app-service.yaml
- tests/unit/helm/ingress_test.go
- tests/unit/helm/serviceaccount_test.go
- tests/unit/helm/teams-app-deployment_test.go
- tests/unit/helm/teams-app-hpa_test.go
- tests/unit/helm/teams-app-service_test.go
~~Updates to `teamsAppSettings.service.name` didn't change the metadata/selector labels in the `teams-app` service or deployment.~~ It was also confusing that changes to `teamsAppSettings.service.name` changed the metadata for the shared ingress and service account as those are not specific to the `teams-app` objects.
This PR aims to change those.
[EDIT]
Selector labels are immutable. To not break existing deployments, we will leave those and just change the `_helpers.tpl` name.
1. Rename `"fiftyone-teams-app.selectorLabels"` to `"teams-app.selectorLabels"` in `_helpers.tpl`
2. Add specific label helpers for the service account and ingress object that are unrelated to `teams-app`
3. Updated tests to reflect the changes made
Checklist
`helm template` for visual inspection
`make …
> fix(charts): AS-101 Decoupling labels and metadata in charts

- .github/workflows/test-docker.yml
Bumps google-github-actions/auth from 2.1.6 to 2.1.7
Replaces [PR 234](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/234)
- bump google-github-actions/auth from 2.1.6 to 2.1.7
Checklist
Not Applicable
See tests below
> bumping google-github-actions from 2.1.6 to 2.1.7

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/app-deployment.yaml
- helm/fiftyone-teams-app/templates/cas-deployment.yaml
- helm/fiftyone-teams-app/templates/plugins-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
Kubernetes supports [startup probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) which seems like a preferred method over `initialDelaySeconds`.
This PR aims to deprecate/remove `initialDelaySeconds` and replace it with actionable `startupProbes`. The probe definitions are the same as the `livenessProbe` and `readinessProbe` definitions, however, the shouldn't cycle pods as often.
Also adding TODO notes about port naming so that we adhere to typical Kubernetes standards (using `<protocol>-<name>` as port names).
* Removes `initialDelaySeconds` from  `livenessProbe` and `readinessProbe` definitions. Also removes the corresponding item in the `values.yaml`.
* Adds `startupProbe` definitions to the templates. …
> fix: AS-276 Adding Startup Probes

- Makefile
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/app-deployment.yaml
- helm/fiftyone-teams-app/templates/cas-deployment.yaml
- helm/fiftyone-teams-app/templates/plugins-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/integration/helm/common_test.go
- tests/integration/helm/helm-topology-spread-constraint_test.go
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
Adding topology spread constraints to the helm chart in order to support customers who may want to utilize it. This includes a flexible way to define the topology constraint including:
* optional label selectors
* optional min domains
* optional node affinity policy / taints
This PR also includes all of the test code, including both unit and integration. 
* A new set of unit tests to test:
* default topology constraints (nil)
* topology constraints with required values set
* topology constraints with overrides set
* A new set of integration test to test basic topology functionality and that helm installs work
* Shareable `_helpers.tpl` for topology constraints to keep things DRY
* Makefile and `values.yml` changes to facilitate the new values and test suite
Checklist
```shell
helm …
```
> feat: AS-321 Adding topology spread constraints

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/app-deployment.yaml
- helm/fiftyone-teams-app/templates/plugins-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
This adds optional `initContainers` to our helm chart. After talking with a CS engineer, the main concern in enabling these is the security scanning of busybox. To aid in this the containers were made optional (disable them via `<svcname>.initContainers.enabled = false`). The image repositories and tags are also configurable. The init script uses `nslookup` to make sure cas is deployed before allowing the application to start.
*Caveat* - NSLookup just makes sure the domain is reachable. We could switch to `wget` or `curl`, the reason for `nslookup` was because it's read-only, doesn't write anything to disk, etc. However, `wget` would be easy to implement as well, but have to make sure the port number is passed through:
```
wget -qO- http://www.example.com:<some port>
```
This adds …
> feat(charts): AS-276 Init Containers

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We've had lots of restarts during deployments lately, so I dove into it a little bit and we're being too agressive with our startup probe timeouts.  Our apps take just a little longer to start than we were allowing them.
increase `startupProbe.periodSeconds` from `5` to `15`
Checklist
N/A - Helm Only Configuration
before change:
```
NAME                             READY   STATUS    RESTARTS        AGE
fiftyone-app-5bc55ff6d-pwpf2     1/1     Running   1 (3m30s ago)   4m26s
fiftyone-app-5bc55ff6d-qmkl2     1/1     Running   0               4m46s
teams-api-5bcbf68c89-4z5tp       1/1     Running   1 (3m51s ago)   4m47s
teams-app-779fb7cf5f-cnqsw       1/1     Running   0               4m46s
teams-app-779fb7cf5f-djjb7       1/1     Running   3 (2m11s ago)   4m17s
teams-cas-7c8cf75f8d-l4qgw …
```
> bump startup probe timeout to 15 seconds

- helm/docs/expose-teams-api.md
- helm/fiftyone-teams-app/templates/ingress.yaml
We shouldn't be setting a catch all `/` as the last route in path-based routing. It can technically lead to non-deterministic routing in very niche cases.
According to [K8s Docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches):
> In some cases, multiple paths within an Ingress will match a request. In those cases precedence will be given first to the longest matching path. If two paths are still equally matched, precedence will be given to paths with an exact path type over prefix path type.
So, the ordering doesn't really matter and if we have two paths that match each other and the `/` route, it could cause issues in certain circumstances. We should just utilize the `defaultBackend` which will handle un-matched routes.
Remove the block about a default …
> fix: AS-328 Default Backends

- docs/custom-plugins.md
Trying to execute this raised this error ERROR: failed to solve: failed to parse stage name "voxel51/fiftyone-app:${TEAMS_VERSION}": invalid reference format unless I changed the ' to ".
> Update custom-plugins.md take 2

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/delegated-operator-executor-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/delegated-operator-executor-deployment_test.go
Adds liveness, readiness, and startup probes to teams-do. This will be a must-have for some users of FOT in order to comply with certain policies.
Adds probes to run `fiftyone delegated list --limit 1 -o liveness`. The `-o liveness` should return 0 results. This will test database connectivity from the pod and should be expanded upon and changed when true liveness/readiness probes are supported from the applciation.
Checklist
Tests updated accordingly.
> fix: AS-330 Adding Probes For teams-do

- tests/unit/helm/teams-app-deployment_test.go
Removes hard-coded strings from helm unit tests.
No functional changes here, just test changes.
set `FIFTYONE_APP_TEAMS_SDK_RECOMMENDED_VERSION` to the values of `chartVersion` instead of hard-coding.
Checklist
```shell
make test-unit-helm
```
> chore(tests): AS-116 Remove Hard-Coded Strings

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/values.yaml
- tests/integration/helm/helm-internal-auth_test.go
- tests/integration/helm/helm-legacy-auth_test.go
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/delegated-operator-executor-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We have been asked to add extra additional secret environment variables into our deployments. This PR aims to do that following a similar pattern that we already use for regular environment variables.
Because the existing functionality behaves like:
```yaml
env:
ENV_VAR_NAME: env-var-value
```
the secret environment variables try to follow a similar pattern:
```yaml
secretEnv:
ENV_VAR_NAME: 
secretName: an-existing-secret
secretKey: the-key-in-the-secret
```
These will then be appended to the `env` list in our helpers.
I am also making a conscious decision not to add support for `envFrom` in this as that seems out of scope for this change.
* In `_helpers.tpl`: Add range loops for `secretEnv` for each application
* Update `values.yaml` accordingly with the new values and example structures …
> feat: AS-288 Extra configurable secrets

- helm/fiftyone-teams-app/templates/api-service.yaml
- helm/fiftyone-teams-app/templates/app-service.yaml
- helm/fiftyone-teams-app/templates/cas-service.yaml
- helm/fiftyone-teams-app/templates/plugins-service.yaml
- helm/fiftyone-teams-app/templates/teams-app-service.yaml
- tests/unit/helm/api-service_test.go
- tests/unit/helm/app-service_test.go
- tests/unit/helm/cas-service_test.go
- tests/unit/helm/plugins-service_test.go
- tests/unit/helm/teams-app-service_test.go
We would like to update `targetPort` in our services to reference the container pod __names__ instead of port numbers ([reference](https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports)). This will allow upstream tools, such as telepresence, to intercept or monitor traffic without needing NET_ADMIN privileges.
Updates services to use `shortname` instead of `containerPort`.
Updates tests accordingly and adds additional name override tests.
Checklist
```shell
make test-unit-helm
```
> chore: changing to port short names

- docker/README.md
- helm/docs/upgrading.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/values.yaml
While looking at the docs, noticed a typo. Let's fix that.
* replace typo "namepace" with "namespace"
Checklist
n/a it's just comments and docs.
> Fix typo "namepace"

- utils/bump-fixtures-common.sh
- utils/bump-fixtures-docker.sh
- utils/bump-fixtures-helm.sh
- utils/bump-fixtures.sh
Over the last few releases, our fixture files in the fiftyone-teams-app-deploy repo have been behind (as opposed to progressing with the rest of the files).
This PR adds a few supporting scripts to support that. I decided to break it up with three scripts:
1. A script to update docker compose fixtures
2. A script to update helm fixtures
3. A script to run the above (i.e. during CI)
The thinking was that it would be easier for an engineer to run them one-off if needed (not that updating files is all that hard).
Three new scripts have been added (see above).
This script updates the `.env` files we use for integration test fixtures
Essentially just uses `sed` with the proper flags to update files in place.
This script updates the `values.yaml` files we use for integration test fixtures …
> feat: AS-352 Updating fixture version numbers

- utils/bump-fixtures-docker.sh
- utils/bump-fixtures-helm.sh
Don't `cat` the file unless you're in dry-run mode.
Don't `cat` the file unless you're in dry-run mode.
Checklist
> chore: Dont print in non-dry-run mode

- helm/fiftyone-teams-app/templates/_helpers.tpl
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/delegated-operator-executor-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We had some missing unit tests in our test suite.  Essentially, we wanted to test what happened to container env vars under the following values changes:
* .Values.teamsAppSettings.fiftyoneApiOverride
* .Values.apiSettings.dnsName
* .Values.teamsAppSettings.dnsName
* .Values.pluginsSettings.enabled
* .Values.secret.name
* .Values.*.service.name
* .Values.*.service.port
During this, a bug was uncovered. We were using go formatting and go was trying to interpret the numerical values of Values.*.service.port. However, `helm --set` passes this as a string. For example:
```shell
helm template . \
--set apiSettings.service.port=8000 \
--set delegatedOperatorExecutorSettings.enabled=true > out
```
Leads to:
```yaml
- name: API_URL
value: "http://teams-api:%!f(int64=8000)"
```
Service was fine: …
> chore: AS-118 Unit tests and bug fix

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Reverts voxel51/fiftyone-teams-app-deploy#277
This should be included as part of version v2.6.0, not v2.5.0.
See [thread here](https://voxel51.slack.com/archives/C05L68A72FM/p1737143630269069)
> Revert "Adds global banner text and color env variables to README"

- .github/workflows/release.yml
[This PR](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/289) was merged into a branch that was subsequently deleted. Just reopening it / pointing it to a new branch.
Bump chart releaser action to 1.7.0.
Checklist
> chore(deps): Update chart-releaser action to 1.7.0

- skaffold.yaml
In many of our deployments, we recommend http to https redirect. We should enforce that our skaffold system also follows these. It's not as realistic as deploying a `FrontendConfig` to `minikube` but, I'm not sure that's possible. However, please let me know if I'm wrong!
Adds `nginx.ingress.kubernetes.io/force-ssl-redirect: "true"` annotation to `skaffold.yaml`.
Checklist
Manual testing. Navigate to `http://local.fiftyone.ai` and ensure that we are automatically redirected to the https endpoint. Also tested via curl:
```shell
$ curl http://local.fiftyone.ai/
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
> chore: AS-159 Adding an http to https redirect

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker-pulls.yml
- .pre-commit-config.yaml
- .tool-versions
- utils/common.sh
- utils/validate-docker-pulls.sh
We require a way to make sure that all of our docker images are pullable before releasing artifacts to the public. We spoke internally about a script that performs this validation - essentially doing a `docker pull` on every image in the output of a `helm template`.
This PR takes a first pass at that - creating a bash script to:
1. Template a helm chart with values file
2. Perform a docker pull on every image it finds
3. Exit 0 or 1, depending on the success of these pulls
* A new script to perform the above
* A new github action to run this script when a PR to main is first opened
* intentionally left out `synchronize`
* A new set of common scripts like logging / common variables that every script uses
Checklist
<details open>
<summary>Testing...</summary>
<br>
Successful!
``` …
```
> ci(artifacts): AS-414 Validate Default Docker Pulls

- .github/workflows/test-docker-pulls.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
It appears the ASDF warnings also, somehow, mess with our unit tests. I have seem a few dependabot PRs fail unit tests but, for no apparent reason. After testing, it appears that pinning to a pre-golang ASDF solves this issue. I pinned it to 0.14.1 as that is the ASDF version I am using locally.
This may need to be cherry-picked into `release/v2.6.0`.
Pins the ASDF version to the bash implementations of ASDF. Newer versions are written in golang which appear to cause issues when ASDF binaries are invoked.
Checklist
> chore: Unit tests require old ASDF

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Reopens https://github.com/voxel51/fiftyone-teams-app-deploy/pull/299 as me so actions pass. Also fix target branch.
Bumps [actions/setup-python](https://github.com/actions/setup-python) from 5.3.0 to 5.4.0.
- [Release notes](https://github.com/actions/setup-python/releases)
- [Commits](https://github.com/actions/setup-python/compare/v5.3.0...v5.4.0)
---
- dependency-name: actions/setup-python dependency-type: direct:production update-type: version-update:semver-minor ...
Checklist
> chore(deps): bump actions/setup-python from 5.3.0 to 5.4.0

- helm/fiftyone-teams-app/templates/_helpers.tpl
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
Our `initContainers` are supposed to enforce an order of events to pod startup. However, our `initContainers` are currently just doing an `nslookup`. That enforces that the DNS name is resolvable, but not that anything is ready to accept traffic. Because of this, we've still been seeing weird crash loops when pods startup. 
This PR changes the entrypoint to do something a bit more sturdy, a `wget` call, to CAS.
Changes the `initContainer` command to:
```shell
"until wget -qO /dev/null \
teams-cas.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/cas/api; 
do echo waiting for cas; 
sleep 2; 
done"
```
* The `-qO /dev/null` will send STDOUT (not STDERR) to /dev/null
* A path, `/cas/api` (same as the liveness probes / readiness probes) is now added to make sure …
> fix(initContainers): AS-498 updating init container entry points

- .github/workflows/pr.yml
- .github/workflows/pre-release-internal-env.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Currently, we publish pre-release artifacts on every push. That means that we're pushing some artifacts which just won't work. We should re-arrange that workflow so that artifact pushes happen only after tests have successfully run.
That also means that we shouldn't push on every branch and PRs have to be submitted before building pre-release artifacts. That seems OK to me!
Restructure workflows to use `workflow_call` instead of `pull_request` events. A new wrapper, similar to fiftyone OSS, will pull those steps together. Affected workflows are:
- test-docker
- test-helm
- test-integration-helm
- pre-release-internal-env
As a final step, the workflow will trigger a pre-release build.
Checklist
> fix: AS-324 implementing path filter

- .tool-versions
- helm/docs/configure-ha-teams-api.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- tests/unit/helm/api-deployment_test.go
We added support for multiple replicas in `teams-api` in our Helm charts, and deployed it to dev.fifityone.ai
This is a followup PR to document how to replicate that process, and to add documentation.
I am not adding documentation for docker-compose environments as we do not typically treat those environments as highly-available
- tests
- docs
> chore: tests and documentation for HA API

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- tests/integration/compose/docker-compose-internal-auth_test.go
- tests/integration/compose/docker-compose-legacy-auth_test.go
- tests/integration/helm/helm-internal-auth_test.go
- tests/integration/helm/helm-legacy-auth_test.go
- tests/integration/helm/helm-topology-spread-constraint_test.go
The banner feature was released in 2.6.0, but the doc updates didn't get pulled into `fiftyone-teams-app-deploy`
This does that.
And (hopefully) pulls forward fixes to helm integration tests.
> chore: bring banner doc updates forward from the future

- helm/fiftyone-teams-app/templates/delegated-operator-instance-deployment.yaml
- tests/unit/helm/delegated-operator-instance-deployment_test.go
While testing a rolling upgrade of this, it appeared that selector labels are immutable. I am removing the `app.teams.operator/instance: {{ $name }}` fields from the labels. The `"app.kubernetes.io/name` already correctly reflects the name of the DO and, therefore, this is redundant.
remove `app.teams.operator/instance: {{ $name }}` labels as they are redundant.
Checklist
> fix: AS-536 multiple do selector labels

- .github/workflows/pr.yml
- .github/workflows/pre-release-internal-env.yml
- .github/workflows/validate-chart-version.yml
A few situations have been getting us into weird situations via automation:
1. The chart versions aren't updated on a release branch. This causes a release branch to push pre-release artifacts as the previous version
2. We haven't been pushing artifacts on pushes to the release-branches, only on the PRs. We should push `-rc` versions after the merge happens and `-sha` versions while the PR is in progress (after tests run successfully)
This PR aims to add a new validation workflow to ensure that, on release branches, the chart.yaml gets updated. It also adds push events to the pre-release-internal-env workflow so that, after merges, `-rc` artifacts get pushed.
1. Add `validate-chart-version` workflow that checks the release branch's name against the `Chart.yaml` version. If they don't …
> fix: as-324 fix pre release

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
While looking at #318 noticed some opportunities for improvement (and clarity).  
* Make consistent across Docker and Helm docs
* Fix formatting errors (backticks replaced by double quotes, remove double double quotes)
* Fix docker service names (users should reference the "real" service names, not the intermediate ones defined in common)
Checklist
Looks good locally in previews
> docs(banners): clean up docker and helm docs for banner texts.

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
we should add the image here (I've been adding it manually to the published helm doc)
adds `fiftyone-teams-cv-full` image to the image list
Checklist
> chore(docs): add `fiftyone-teams-cv-full` to image list

- .pre-commit-config.yaml
- docker/README.md
- docs/validating-deployment.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
We have some utilities to validate if a deployment is ready or not. We should being writing those down and having a `validation` page where users can say "is my deployment ready?". This PR adds that page and then updates the docker/helm pages to reference it.
Adds a new `validating-deployment` page. As of now, this page mainly refers to `fom.test_api_connection()`, however, it could be extended to more detailed URI/Websocket/etc. checks should the need arise.
Checklist
> chore(docs): AS-550 Adding Validation Docs

- docs/custom-mongodb-permissions.md
Document custom Mongo permissions spec, this gets hit fairly frequently
This is just a brief auxiliary doc page.
Checklist
> Add custom mongo permissions spec

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
ASDF actions were failing due to the GoLang rewrite. The old action emitted a huge warning that sometimes made it's way into STDOUT and messed with test results. This was solved via a PR linked in the [Jira Ticket](https://voxel51.atlassian.net/browse/AS-506).
> [!NOTE]
> I'm only bumping the action where versions were specifically pinned via the below. This is because dependabot will bump the other versions when a release is cut. We can go back and switch these back to release versions at that time, but it felt good to do away with the 0.14.1 pin.
```
uses: asdf-vm/actions/install@v3.0.2
with:
asdf_branch: v0.14.1
```
Uses the GitHub sha of the new/merged/fixed action.
Will be tested via actions for pre-commit and all tests.
> build(asdf): AS-506 ASDF install action bump

- docker/README.md
- docker/docs/configuring-gpu-workloads.md
- helm/docs/configuring-gpu-workloads.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
We have an increasing amount of stakeholders (internal and external) utilizing GPUs. We should document how GPUs can be made accessible to either K8s pods or docker containers. While reviewing this PR, I also noticed that the `## Advanced Configuration` section of the compose docs were out of order, so I figured we could fix it.
1. Adds GPU documentation for both docker compose and kubernetes
1. For both, show an example with teamd-do 
2. For K8s, only show a GKE example
1. Re-orders the `## Advanced Configuration` of the compose docs
2. Changes the `FiftyOne Enterprise Plugins` header in the docker docs to `Plugins` to match the helm docs
Checklist
> docs(gpus): AS-561 Document gpu workloads

- helm/docs/configuring-delegated-operators.md
While reviewing the release PR to main, also notice some markdown formatting that be easier for readers to comprehend (when looking at the raw text and the rendered page too).
1. indents
Checklist
I looked at the compose docs for the delegated operators and they are good.
> docs(helm): fix indent of yaml code blocks to nest under lists.

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
Internally, our pods are taking longer to start up. While this is a problem in itself, our chart should account for that known situation. This doubles the number of thresholds that has to fail before restarting the pod.
A failure threshold of 10 with a period of 15 seconds is 150 seconds dedicated to startup in the worst case scenario.
Increasing the failure threshold seems more appropriate than increasing the period between checks.
* Increases the default `failureThresold` for `teams-api` from 5 to 10.
* Updates unit tests to reflect changes
Checklist
```shell
make test-unit-helm
```
Helm templating returns:
```yaml
[... other templates ...]
startupProbe:
httpGet:
path: /health/
port: teams-api
failureThreshold: 10
periodSeconds: 15
timeoutSeconds: 5
[... other templates ...]
```
> chore(teams-api): AS-579 increase startup timeout

- helm/docs/configuring-delegated-operators.md
While migrating from `delegatedOperatorExecutorSettings` to `delegatedOperatorDeployments`, I noticed that the docs could be improved.
* helm delegatedOperatorDeployments docs
Checklist
The helm docs were already good!
> Moar Delgated Operator Configuration Docs

- helm/docs/configure-workload-identity-federation.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
We have been asked what our minimum permissions sets are and now we are in a place to test those. This PR goes through the minimum permission sets that we need to deploy successfully on GKE. It walks through:
1. Adding a service account in GCP
2. Making custom roles in GCP
3. Assigning those roles and memberships to the service account
4. Creating IAM bindings and annotations so GKE and GCP can authenticate
Adds a new document, `configure-workload-identity-federation.md`. This document outlines the above permissions. It does so in both gcloud CLI and via terraform.
This also removes the `deploying on GKE` section from our main helm README.
This was only done for K8s as it doesn't exist in docker docs. 
Checklist
<details><summary>Gcloud testing</summary>
I ran through the below script …
> docs(wif): as-584 adding minimum permission set for gke wif

- README.md
- docker/README.md
- docker/docs/configuring-delegated-operators.md
- docker/docs/configuring-gpu-workloads.md
- docker/docs/configuring-plugins.md
- docker/docs/configuring-proxies.md
- docker/docs/configuring-snapshot-archival.md
- docker/docs/expose-teams-api.md
- docker/docs/known-issues.md
- docker/docs/upgrading.md
- docs/Release-v2.1.0-Database-Migration.md
- docs/custom-mongodb-permissions.md
- docs/custom-plugins.md
- docs/validating-deployment.md
- helm/README.md
- helm/docs/configure-ha-teams-api.md
- helm/docs/configure-workload-identity-federation.md
- helm/docs/configuring-delegated-operators.md
- helm/docs/configuring-gpu-workloads.md
- helm/docs/configuring-plugins.md
- helm/docs/configuring-proxies.md
- helm/docs/configuring-snapshot-archival.md
- helm/docs/expose-teams-api.md
- helm/docs/known-issues.md
- helm/docs/plugins-storage.md
- helm/docs/upgrading.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/local-self-signed-example/README.md
We add logos to most pages, however, we were omitting alt-text from them. We can add the alt-text to follow best practices. Additionally, I came across a few pages that were missing he headers. Now seems like a good time to add them!
* Removes the `markdownlint-disable alt-text` from headers
* Adds alt-text to each logo / FiftyOne word image
* Adds headers in documents that were missing headers
Checklist
Local previews of the markdown and previews on GitHub.
> docs: AS-597 Add alt-text to image headers

- docs/custom-plugins.md
Addresses the merge conflicts in https://github.com/voxel51/fiftyone-teams-app-deploy/pull/348.
```shell
git checkout release/v2.7.2
git checkout -b afoley/release-v2.7.2-merge-conflicts
git merge main
```
And then address conflicts appropriately.
Checklist
> Address main <-> release/v2.7.2 Merge Conflicts

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker-pulls.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
- Makefile
`asdf local` is deprecated and removed in newer versions. We can switch to `asdf set`. We can also bump to the newer action to avoid that deprecation notice which munges STDOUT.
* Bump ASDF action to use the latest SHA
* Migrate from `asdf local` to `asdf set`
> chore(asdf): AS-596 utilize asdf set and bump asdf action

- helm/docs/upgrading.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/_helpers.tpl
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/app-deployment.yaml
- helm/fiftyone-teams-app/templates/plugins-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
When evicting nodes, kubernetes considers the pods [quality of service](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/).
QoS has three classes:
* [Guaranteed](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#guaranteed)
* [Burstable](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#burstable)
* [BestEffort](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort)
These classes are derived from the resource constraints on each container in the pod, including init and ephemeral containers. We should give customers the ability to define these QoS classes by making sure every container has resource settings available to them from the `values.yaml`.
1. Updates `_helpers.tpl` to allow for resource constraints:
```yaml
{{- if …
```
> chore(helm): AS-628 adding resources to init containers

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/values.yaml
While helping a customer recently, I realized that we never set/documented the `apiSettings.replicaCount`. We should add it with a default value of one.
Adds `apiSettings.replicaCount: 1` to `values.yaml`.
Checklist
> chore(helm): AS-638 add API replica count

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/serviceaccount.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/serviceaccount_test.go
We currently don't allow users to [opt out of API credentials](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting). We should add that as a configuration setting since nothing FOE does requires K8s API access.
To comply with current K8s deployments and K8s standards, this should default to true with an explicit "opt out" type of workflow.
* Adds `automountServiceAccountToken` setting to the helm service account
* Adds tests to validate the configuration of `automountServiceAccountToken`
Checklist
Go tests and `helm template`:
```yaml
$ helm template .
.
.
apiVersion: v1
kind: ServiceAccount
metadata:
name: fiftyone-teams
namespace: fiftyone-teams
labels:
helm.sh/chart: fiftyone-teams-app-2.8.0 …
```
> chore(helm): AS-631 add automount token for service accounts

- docker/docs/configuring-gpu-workloads.md
GPU smoketest example uses CPU container, not GPU container
fix typo
Checklist
The helm example doesn't need an update as it uses an abstract envvar/name
doc update
> fix: use gpu container in GPU smoketest example

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We discussed in slack defaulting the `initContainers.allowPrivilegeEscalation` and `initContainers.resources` to known good values. These are very small pods and can run in secure ways, so we can default securely.
* Default `initContainers.allowPrivilegeEscalation=false`
* Default `initContainers.resources` to `10m` and `128Mi`
Checklist
Go tests updated
```
initContainers:
- name: init-cas
image: docker.io/busybox:stable-glibc
command:
- 'sh'
- '-c'
- "until wget -qO /dev/null teams-cas.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/cas/api; do echo waiting for cas; sleep 2; done"
resources:
limits:
cpu: 10m
memory: 128Mi
requests:
cpu: 10m
memory: 128Mi
securityContext:
allowPrivilegeEscalation: false
```
> chore(helm): AS-652 set default values

- helm/docs/upgrading.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
In https://github.com/voxel51/fiftyone-teams-app-deploy/pull/362, we decided to default to a secure configuration for `initContainers`. This follows a similar mentality and enforces that the containers run as UID 1000 and disabled running as root. It also seems like a good idea to update our `upgrading` doc to reflect these changes so that any users already configuring `initContainers` aren't impacted negatively.
1. Updates `initContainer.containerSecurityContext` to
```yaml
containerSecurityContext:
allowPrivilegeEscalation: false
runAsNonRoot: true
runAsUser: 1000
```
1. Updates `upgrading.md` to reflect the new defaults
2. Updates unit tests accordingly
Checklist
Go tests and `helm template` (shown below)
```yaml
initContainers:
- name: init-cas
image: docker.io/busybox:stable-glibc …
```
> chore(helm): AS-650 Run `initContainers` as non-root

- helm/docs/configuring-delegated-operators.md
We've seen some instances of our `teams-do` migration leaving two instances floating around: one with resources attached and one without.  The `builtin` operator no longer has a backing replicaset so it hogs the queue. We should add steps to remove it from the application.
Add docs on how to remove the `builtin` orchestrator after the migration.
Checklist
> docs(teams-do): Update migration docs to include dropping of builtin

- docker/docs/expose-teams-api.md
- helm/docs/expose-teams-api.md
Documenting API server configuration vars added in https://github.com/voxel51/voxel-hub/pull/1717
Added description and default for each of the allowed variables, to `expose-teams-api.md`
Checklist
doc only
> FOEPD-1089 document server configs

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker-pulls.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Like https://github.com/voxel51/fiftyone-teams-app-deploy/pull/367 but from a GH user that can run the tests
Bumps [actions/setup-python](https://github.com/actions/setup-python) from 5.5.0 to 5.6.0.
- [Release notes](https://github.com/actions/setup-python/releases)
- [Commits](https://github.com/actions/setup-python/compare/v5.5.0...v5.6.0)
---
- dependency-name: actions/setup-python dependency-version: 5.6.0 dependency-type: direct:production update-type: version-update:semver-minor ...
Checklist
> chore(deps): bump actions/setup-python from 5.5.0 to 5.6.0

- .github/workflows/test-docker-pulls.yml
A PR Check on #374 failed.  I was confused by the name "Tests - Artifact Pulls / unit-helm (pull_request)". In the workflow, we don't run unit-helm, we run `validate-docker-pulls.sh`. I suspect this was a result of a copy/paste.
* worklow
* update job name
Checklist
n/a
> chore: rename job in `.github/workflows/test-docker-pulls.yml`

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/fiftyone-teams-app/templates/api-deployment.yaml
- helm/fiftyone-teams-app/templates/app-deployment.yaml
- helm/fiftyone-teams-app/templates/cas-deployment.yaml
- helm/fiftyone-teams-app/templates/delegated-operator-executor-deployment.yaml
- helm/fiftyone-teams-app/templates/delegated-operator-instance-deployment.yaml
- helm/fiftyone-teams-app/templates/plugins-deployment.yaml
- helm/fiftyone-teams-app/templates/teams-app-deployment.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/delegated-operator-executor-deployment_test.go
- tests/unit/helm/delegated-operator-instance-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
There are some cases where a customer needs to use a `Recreate` strategy instead of the default `RollingUpgrade` strategy on their deployment objects. For example, if a customer has a specific hardware limit that rolling upgrades can't accommodate. We should allow these for those cases and for all of the deployment objects we provision. This PR aims to add that capability.
*NOTE*
For `delegatedOperatorDeployments`, the following is a possible case:
```yaml
delegatedOperatorDeployments:
template:
updateStrategy:
type: RollingUpgrade
rollingUpgrade:
maxUnavailable: 5
deployments:
teamsDo: {}
teamsDoTwo:
updateStrategy:
type: Recreate
```
This would result in 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: teams-do-two
namespace: fiftyone-teams
labels:
helm.sh/chart: …
```
> chore(helm): AS-688 adding deployment strategy parameters

- CONTRIBUTING.md
- docker/README.md
- docker/docs/upgrading.md
- helm/docs/upgrading.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
- helm/gke-example/values.yaml
- helm/values.yaml
- skaffold.yaml
- tests/fixtures/docker/compose.override.yaml
- tests/fixtures/helm/integration_values.yaml
- tests/integration/compose/common_test.go
Once upon a time, initial installations required that `FIFTYONE_DATABASE_ADMIN=true`. This is no longer the case as our backend systems have changed. This set of docs sometimes caused confusion and accidental DB modifications (if someone forgot to turn it off). It's really only required for database migrations which now only happen during upgrades. We should update our docs, tests, and references to remove that initial setting.
1. Removes the `## Initial install vs upgrades` sections and changes them to `Upgrading`
2. Adds a `### Version 2.9+ Installation Changes` to each toolchain's README documenting the high level change
3. Moves the `fiftyone migrate` behavior to `upgrading.md` and add parity between helm and docker
4. Removes the `FIFTYONE_DATABASE_ADMIN=true` from integration tests …
> docs(DATABASE_ADMIN): AS-578 remove `FIFTYONE_DATABASE_ADMIN=true`

- docker/README.md
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/README.md.gotmpl
Recently, we reordered our [deprecation docs](https://docs.voxel51.com/deprecation.html) to have the newest stuff on top. We should apply that to our `Important` sections in our deployment READMEs.
Reorders the `Important` sections to have the newest stuff (2.9.0) at the top and the oldest stuff (2.0.0) at the bottom.
Checklist
Docs only.
> docs(important): Reorder the IMPORTANT section of the docs

- helm/docs/configuring-plugins.md
Links to the custom plugins doc are broken due to a comma:  `,/plugins-storage.md`. Changed to ` ./plugins-storage.md` to fix.
> Broken link fix

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We can drop all capabilities for `initContainers` as they don't do any privileged linux actions. This makes deploying them a bit safer.
Sets the default `initContainer.containerSecurityContext` to
```yaml
containerSecurityContext:
allowPrivilegeEscalation: false
capabilities:
drop: [ALL] # ADDED
runAsNonRoot: true
runAsUser: 1000
```
Checklist
Go tests were updated.
Helm template results below:
```yaml
initContainers:
- name: init-cas
image: docker.io/busybox:stable-glibc
command:
- 'sh'
- '-c'
- "until wget -qO /dev/null teams-cas.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/cas/api; do echo waiting for cas; sleep 2; done"
resources:
limits:
cpu: 10m
memory: 128Mi
requests:
cpu: 10m
memory: 128Mi
securityContext:
allowPrivilegeEscalation: false …
```
> chore(helm): AS-687 default capabilities.drop for initContainers

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/cas-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
Our pods take a while to start. Let's increase their startup probes.
Checklist
> chore(helm): increase startup probe

- .github/workflows/pre-commit.yml
- .github/workflows/test-docker-pulls.yml
- .github/workflows/test-docker.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-integration-helm.yml
Newer is better 
- `perl -pi -e 's/9cd779f40fe38688dd19505ccbc4eaaf018b44e7/1902764435ca0dd2f3388eea723a4f92a4eb8302/g' *`
Checklist
This version is already used in other repos, including the internal-helm repo
> chore: bump asdf-vm/actions to 1902764435ca0dd2f3388eea723a4f92a4eb8302

- tests/integration/compose/common_test.go
- tests/integration/compose/docker-compose-internal-auth_test.go
- tests/integration/compose/docker-compose-legacy-auth_test.go
I've noticed recently that, as our packages get bigger, it takes them longer to start up. Let's make our tests less flakey by adding logging retries.
* Adds the `checkContainerLogsWithRetries` function which re-attempts to get logs
* Switches the original test implementation of `get_logs` with `checkContainerLogsWithRetries`
Checklist
> chore(integration): AS-696 address integration test flakes

- .github/workflows/pre-release-internal-env.yml
- helm/fiftyone-teams-app/values.yaml
In a prior PR, we had pinned `helm` versions in our pre-release flow to `3.17.3` because there was an issue with OCI/HTTPS repos. This appears to be fixed in 3.18.1. This PR will serve as additional testing to ensure that everything works as expected.
Removes the `3.17.3` pin on helm in the `pre-release-internal-env` workflow.
Checklist
```shell
% helm version
version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}
% gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin "https://us-central1-docker.pkg.dev"
Error: invalid reference: invalid registry "https://us-central1-docker.pkg.dev"
alexanderfoley@Alexanders-MacBook-Pro fiftyone-teams-app-deploy % 
% helm version …
```
> chore(pre-release): AS-701 test pre-release charts

- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/api-deployment_test.go
- tests/unit/helm/app-deployment_test.go
- tests/unit/helm/plugins-deployment_test.go
- tests/unit/helm/teams-app-deployment_test.go
We set expected resource requests/limits for the initContainer CPU/memory. We should add it for [ephemeral-storage](http://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage) as well.
Adds `ephemeral-storage` defaults to each `initContainer`
Updates tests accordingly
Checklist
> chore(initContainers): Smaller ephemeral storage request

- helm/fiftyone-teams-app/Chart.yaml
- helm/fiftyone-teams-app/README.md
- helm/fiftyone-teams-app/templates/NOTES.txt
- helm/fiftyone-teams-app/templates/ingress.yaml
- helm/fiftyone-teams-app/values.yaml
- tests/unit/helm/ingress_test.go
As discussed, any Kubernetes version older than 1.30.0 is EOL and no longer supported by kubernetes. Cloud providers may support as far back as 1.27. For example, [Google supports 1.27](https://cloud.google.com/kubernetes-engine/docs/release-schedule).
In my opinion, taking a stance that we support non-EOL kubernetes versions seems like a decent stance to take. I am open to discussions on the PR!
Moves our minimum version from 1.18 to 1.30 in accordance with the [kubernetes release lifecycle](https://kubernetes.io/releases/).
> [!NOTE]
> We will need to make a corresponding `voxel51/fiftyone` PR as well to update deprecation.voxel51.com.
Checklist
Docs only PR
> chore(helm): AS-711 remove support for old kubernetes versions

- utils/validate-docker-pulls.sh
Last release, we realized that the `docker pull` to validate if an image exists or not takes a LONG time. Luckily, there is an **experimental** docker command: [docker manifest](https://docs.docker.com/reference/cli/docker/manifest/inspect/)
This can help us check the manifest, not the pull, to see if an image exists on the remote.
Changes the `docker pull` command to `docker manifest inspect`
Checklist
<details><summary>Testing Failures</summary>
```shell
INFO: Validated docker.io/busybox:stable-glibc successfully.
ERROR: Could not validate voxel51/fiftyone-app:v2.11.1!
ERROR: Could not validate voxel51/fiftyone-app-gpt:v2.11.1!
ERROR: Could not validate voxel51/fiftyone-app-torch:v2.11.1!
ERROR: Could not validate voxel51/fiftyone-teams-api:v2.11.1!
ERROR: Could not validate …
```
> chore(utils): AS-788 speed up docker image checking

- helm/values.yaml
This PR essentially reopens [this lost pr](https://github.com/voxel51/fiftyone-teams-app-deploy/pull/398/files).
We had a typo env var in our example `values.yaml` file. The `FIFTYONE_APP_INSTALL_FIFTYONE_OVERRIDE` is actually what overrides the `pip install` string, the `FIFTYONE_TEAMS_VERSION_OVERRIDE` is shown in the footer.
Checklist
> chore(values): AS-728 refix example

- utils/get-helm-chart-version.sh
This code chunk has been passed around a lot internally. Let's make it a first class citizen. Sometimes we need to look up a dependent chart's version from GAR and this script helps us do that.
Adds `utils/get-helm-chart-version.sh` which looks up the helm chart from either Git SHA of the current HEAD or from the branch name.
Checklist
> chore(utils): AS-822 codify GAR search scripts

- docs/orchestrators/configuring-anyscale-orchestrator.md
- docs/orchestrators/configuring-databricks-orchestrator.md
While we have not gotten to the bottom of an issue between Databricks/Anyscale and MongoDB Atlas, we will advise (and default to) setting the max number of processes limit to 4.
Also tweaked some other notes
Checklist
N/A
Doc only
> Advise capping max processes in DB,AS to 4
